/**
 * src/db/client.ts — Site DB query helpers (async, Drizzle / @astrojs/db)
 *
 * All functions are async — @astrojs/db uses libsql under the hood.
 * Tables and query helpers are imported from 'astro:db' (virtual module
 * generated by the @astrojs/db integration from db/config.ts).
 */

import {
  db,
  Page, PageContent, SeoMeta, SiteConfig, Menu, MenuItem,
  ContentDocument, ContentCollection, ContentAuthor,
  eq, and, isNull, asc, desc,
} from 'astro:db';

import type {
  SiteConfig as SiteConfigType,
  Page as PageType,
  PageContent as PageContentType,
  PageWithContent,
  SeoMeta as SeoMetaType,
  Menu as MenuType,
  MenuItem as MenuItemType,
  MenuItemWithChildren,
  MenuWithItems,
  ContentDocument as ContentDocumentType,
  ContentCollection as ContentCollectionType,
  ContentAuthor as ContentAuthorType,
  ContentCard,
  ContentType,
  ContentStatus,
  ListDocumentsOptions,
} from './types.js';

// ── SiteConfig defaults (returned when the row doesn't exist yet) ─────────────

const SITE_CONFIG_DEFAULTS: SiteConfigType = {
  id: 'main', name: 'My Site', domain: null,
  locale: 'en', timezone: 'UTC', status: 'active',
  tagline: null, description: null, base_url: null, theme: 'light',
  primary_color: null, secondary_color: null, logo_url: null, favicon_url: null,
  social_twitter: null, social_linkedin: null, social_github: null,
  social_youtube: null, social_instagram: null, social_facebook: null,
  contact: {}, meta: {},
  layout_variant: 'full-width',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function buildMenuTree(flat: (MenuItemType & { page_path?: string | null })[]): MenuItemWithChildren[] {
  const byId = new Map(flat.map((item) => [item.id, { ...item, children: [] as MenuItemWithChildren[] }]));
  const roots: MenuItemWithChildren[] = [];
  for (const node of byId.values()) {
    if (node.parent_id) {
      byId.get(node.parent_id)?.children.push(node);
    } else {
      roots.push(node);
    }
  }
  return roots;
}

// ── Site layer ────────────────────────────────────────────────────────────────

/** Returns the site_config row, or safe defaults when not yet created. */
export async function getSiteConfig(): Promise<SiteConfigType> {
  const rows = await db.select().from(SiteConfig).where(eq(SiteConfig.id, 'main'));
  const row = rows[0];
  if (!row) return SITE_CONFIG_DEFAULTS;
  return {
    ...(row as unknown as SiteConfigType),
    contact:        (row.contact        as Record<string, unknown>) ?? {},
    meta:           (row.meta           as Record<string, unknown>) ?? {},
    layout_variant: (row.layout_variant as string | null)           ?? 'full-width',
  };
}

/** Returns a published page with its current locale content, or null. */
export async function getPageByPath(path: string, locale = 'en'): Promise<PageWithContent | null> {
  const pages = await db.select().from(Page)
    .where(and(eq(Page.path, path), isNull(Page.deleted_at)));
  const page = pages[0];
  if (!page) return null;

  const contents = await db.select().from(PageContent)
    .where(and(
      eq(PageContent.page_id, page.id),
      eq(PageContent.locale, locale),
      eq(PageContent.is_current, true),
    ));
  const content = contents[0] ?? null;

  return {
    ...(page as unknown as PageType),
    ref_id:   page.ref_id   ?? null,
    ref_type: page.ref_type ?? null,
    content: content
      ? { ...(content as unknown as PageContentType), body: (content.body as unknown[]) ?? [] }
      : null,
  };
}

/** Returns all non-deleted pages ordered by position. */
export async function getPageTree(): Promise<PageType[]> {
  const rows = await db.select().from(Page)
    .where(isNull(Page.deleted_at))
    .orderBy(asc(Page.position));
  return rows as unknown as PageType[];
}

/** Returns published children of a parent (null = root-level pages). */
export async function getChildPages(parentId: string | null): Promise<PageType[]> {
  const rows = parentId === null
    ? await db.select().from(Page)
        .where(and(isNull(Page.parent_id), isNull(Page.deleted_at), eq(Page.status, 'published')))
        .orderBy(asc(Page.position))
    : await db.select().from(Page)
        .where(and(eq(Page.parent_id, parentId), isNull(Page.deleted_at), eq(Page.status, 'published')))
        .orderBy(asc(Page.position));
  return rows as unknown as PageType[];
}

/** Returns a menu with its full item tree (page paths joined). */
export async function getMenu(handle: string): Promise<MenuWithItems | null> {
  const menus = await db.select().from(Menu).where(eq(Menu.handle, handle));
  const menu = menus[0];
  if (!menu) return null;

  // Join menu items with their linked page paths
  const rows = await db
    .select({ item: MenuItem, page_path: Page.path })
    .from(MenuItem)
    .leftJoin(Page, eq(MenuItem.page_id, Page.id))
    .where(eq(MenuItem.menu_id, menu.id))
    .orderBy(asc(MenuItem.position));

  const items = rows.map((r) => ({
    ...(r.item as unknown as MenuItemType),
    is_external:     Boolean(r.item.is_external),
    open_in_new_tab: Boolean(r.item.open_in_new_tab),
    is_cta:          Boolean(r.item.is_cta),
    page_path:       r.page_path ?? null,
  }));

  return { ...(menu as unknown as MenuType), items: buildMenuTree(items) };
}

/** Returns SEO meta for a page + locale, or null. */
export async function getSeoMeta(pageId: string, locale = 'en'): Promise<SeoMetaType | null> {
  const rows = await db.select().from(SeoMeta)
    .where(and(eq(SeoMeta.page_id, pageId), eq(SeoMeta.locale, locale)));
  return rows[0] ? (rows[0] as unknown as SeoMetaType) : null;
}

// ── Content document layer ────────────────────────────────────────────────────

/** Returns a full ContentDocument by id, or null. */
export async function getDocument(id: string): Promise<ContentDocumentType | null> {
  const rows = await db.select().from(ContentDocument)
    .where(and(eq(ContentDocument.id, id), isNull(ContentDocument.deleted_at)));
  return rows[0] ? (rows[0] as unknown as ContentDocumentType) : null;
}

/** Returns a published ContentDocument by slug + locale, or null. */
export async function getDocumentBySlug(slug: string, locale = 'en'): Promise<ContentDocumentType | null> {
  const rows = await db.select().from(ContentDocument)
    .where(and(
      eq(ContentDocument.slug, slug),
      eq(ContentDocument.locale, locale),
      eq(ContentDocument.status, 'published'),
      isNull(ContentDocument.deleted_at),
    ));
  return rows[0] ? (rows[0] as unknown as ContentDocumentType) : null;
}

/** Returns a filtered list of ContentDocuments. */
export async function listDocuments(opts: ListDocumentsOptions = {}): Promise<ContentDocumentType[]> {
  const { content_type, status = 'published', locale, is_featured, limit = 20, offset = 0 } = opts;
  const conditions = [eq(ContentDocument.status, status), isNull(ContentDocument.deleted_at)];
  if (content_type) conditions.push(eq(ContentDocument.content_type, content_type));
  if (locale)       conditions.push(eq(ContentDocument.locale, locale));
  if (is_featured)  conditions.push(eq(ContentDocument.is_featured, true));

  const rows = await db.select().from(ContentDocument)
    .where(and(...conditions))
    .orderBy(desc(ContentDocument.published_at))
    .limit(limit)
    .offset(offset);
  return rows as unknown as ContentDocumentType[];
}

/** Returns lightweight ContentCard projections for list/grid views. */
export async function listContentCards(opts: ListDocumentsOptions = {}): Promise<ContentCard[]> {
  const docs = await listDocuments(opts);
  return docs.map((d) => ({
    id:                d.id,
    content_type:      d.content_type as ContentType,
    title:             d.title,
    subtitle:          d.subtitle ?? null,
    excerpt:           d.excerpt ?? null,
    slug:              d.slug ?? null,
    locale:            d.locale,
    cover_url:         (d.cover_image as { url?: string } | null)?.url ?? null,
    status:            d.status as ContentStatus,
    is_featured:       Number(d.is_featured),
    is_premium:        Number(d.is_premium),
    published_at:      d.published_at ?? null,
    reading_time_mins: d.reading_time_mins ?? null,
    word_count:        d.word_count ?? null,
    tags:              (d.tags as { name: string; slug?: string; color?: string }[]) ?? [],
    collection_ids:    (d.collection_ids as string[]) ?? [],
    author_name:       (d.authors as { name?: string }[])?.[0]?.name ?? null,
    author_avatar:     (d.authors as { avatar?: { url?: string } }[])?.[0]?.avatar?.url ?? null,
    schema_org_type:   d.schema_org_type ?? null,
  }));
}

/** Returns a ContentCollection by id, or null. */
export async function getContentCollection(id: string): Promise<ContentCollectionType | null> {
  const rows = await db.select().from(ContentCollection).where(eq(ContentCollection.id, id));
  return rows[0] ? (rows[0] as unknown as ContentCollectionType) : null;
}

/** Returns all ContentCollections, optionally filtered by content_type. */
export async function listContentCollections(contentType?: ContentType): Promise<ContentCollectionType[]> {
  const rows = contentType
    ? await db.select().from(ContentCollection)
        .where(eq(ContentCollection.content_type, contentType))
        .orderBy(asc(ContentCollection.sort_order))
    : await db.select().from(ContentCollection)
        .orderBy(asc(ContentCollection.sort_order));
  return rows as unknown as ContentCollectionType[];
}

/** Returns a ContentAuthor by id, or null. */
export async function getContentAuthor(id: string): Promise<ContentAuthorType | null> {
  const rows = await db.select().from(ContentAuthor).where(eq(ContentAuthor.id, id));
  return rows[0] ? (rows[0] as unknown as ContentAuthorType) : null;
}

/** Returns all ContentAuthors. */
export async function listContentAuthors(): Promise<ContentAuthorType[]> {
  const rows = await db.select().from(ContentAuthor).orderBy(asc(ContentAuthor.name));
  return rows as unknown as ContentAuthorType[];
}

// Re-export types for convenience
export type { SiteConfigType as SiteConfig, PageWithContent, SeoMetaType as SeoMeta, MenuWithItems, ListDocumentsOptions };
